### ISSUE TITLE
Ability to use parsers individually 

### ISSUE THREAD

**Issue by Piyushhbhutoria** [GuardatiSimone/messaging-chat-parser#2]
how can I disable telegram parser and use only WhatsApp parser? or vice-versa? 

I don't have telegram export and the code is failing is trying to parse telegram export.

**Comment by pistocop** [comment]
Hi @Piyushhbhutoria ,

## ✔️ Independent parsing:

[Here](https://github.com/GuardatiSimone/messaging-chat-parser#-usage) in the **⚙ Usage** chapter you could find how the two parsers works autonomously [1].

I report here for the sake of simplicity:
**WhatsApp**:
`python ./src/whatsapp_parser.py --session_token "<|endoftext|>" --delta_h_threshold 4 --user_name <user_name>`

**Telegram:**
`python ./src/telegram_parser.py --session_token "<|endoftext|>" --delta_h_threshold 4`

-------
## 💡 Tip

I think your problem isn't with [messaging-chat-parser](https://github.com/GuardatiSimone/messaging-chat-parser) repo, but with [pistoBot](https://github.com/GuardatiSimone/pistoBot) - and in particular the related [colab notebook](https://colab.research.google.com/drive/1T4-Gk-mlAWJkX9RuRd3_EiS5JBP5UvyV?usp=sharing).

If so, I have just released a [patch](https://github.com/GuardatiSimone/messaging-chat-parser/commit/90abf7e5b028ed567e74a008a375312012d66f0f).  Now you can run [this](https://colab.research.google.com/drive/1T4-Gk-mlAWJkX9RuRd3_EiS5JBP5UvyV#scrollTo=y3_N2WUso_XI&line=4&uniqifier=1) cell and get the file _all-messages.txt_ even if telegram data isn't provided [2].

👉 So try to re-run the notebook from scratch and everything should be ok now.

Let me know!

-------
[1] Look also at the bottom of the README, under "📅 Parsing data with custom values", for an additional example with the injection of custom Datetime format)

[2] The notebook cell still prompt a "FileNotFoundError" error but at the bottom the `joiner.py` should work well and prompt an alert like: `[joiner.py][WARNING]: File ./data/chat_parsed/telegram-chats.txt provided but not found`. (it's an unaesthetic behavior and maybe I will fix in the future)
