### ISSUE TITLE
Wrong datetime format

### ISSUE THREAD

**Issue by danilotomaccio** [GuardatiSimone/messaging-chat-parser#5]
I get the error `ValueError: time data '04/01/2017, 10:31 'does not match format'%d/%m/%y, %H:%M'`. The problem seems to be with the `%y` that should be `%Y`

My Python version is 3.9.5
My OS is MacOS

**Comment by pistocop** [comment]
Hi @danilotomaccio,

You are right, in your case the `%Y` specific is the right one.

Unfortunately, Whatsapp exports the data in different formats depending on the user geographical zone (and maybe the version too).

For this reason, the script takes an additional parameter named `--time_format` where you can change the default DateTime parser.

You can find more info about this parameter on:
- The [readme](https://github.com/pistocop/messaging-chat-parser/blame/master/README.md#L70)
- The [code](https://github.com/pistocop/messaging-chat-parser/blob/edfa4d2f7b7552c50adad5e773e436fab60ece1f/src/whatsapp_parser.py#L111)

Regards,
Simone
