### ISSUE TITLE
user not added to parsed messages 

### ISSUE THREAD

**Issue by partylikeits1983** [GuardatiSimone/messaging-chat-parser#6]
user not added to parsed messages 

in the folder chat_parsed, in both files, telegram-chats.txt and wa-chats.txt the only messages that appear are [others]

**Comment by ShaunLWM** [comment]
https://github.com/pistocop/messaging-chat-parser/pull/7

**Comment by pistocop** [comment]
It looks like Telegram had added the "user" string as the default prefix of each "from_id" field of the dump.

Thanks to @ShaunLWM the problem it's fixed now!
